# Generated by Django 3.1 on 2020-08-11 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200811_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='slug',
            field=models.CharField(default='1', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='url',
            field=models.CharField(max_length=1023, validators=[django.core.validators.RegexValidator(regex='^(?:http(s)?:\\/\\/)?[\\w.-]+(?:\\.[\\w\\.-]+)+[\\w\\-\\._~:/?#[\\]@!\\$&\\(\\)\\*\\+,;=.]+$')]),
        ),
    ]
